### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by MacgyverJohnson** [EricZimmerman/AppCompatCacheParser#1]
Hello there @EricZimmerman 
Is it possible to delete specific apps from AppCompatCache?data is in binary format...
My intention being removing trace that a particular application was ever run in a PC?
Thanks

**Comment by EricZimmerman** [comment]
why remove it (rhetorical question...)? it may be possible, but ive never tried

**Comment by MacgyverJohnson** [comment]
The command: 
`rundll32.exe kernel32.dll,BaseFlushAppcompatCache`
flushes AppCompatCache completely.... I wanted to know if it was possible to selectively delete entries?
(purely Academic purpose )
Thanks
