### ISSUE TITLE
Output File Name

### ISSUE THREAD

**Issue by PolarBearGod** [EricZimmerman/AppCompatCacheParser#2]
I was wondering if there is a way now (or maybe as a feature request) to output the file to a specified name? If I attempt such things with the `--csv` switch, it just creates a folder with the name and dumps the file there.

While I can obviously rename the file after output via script, I was hoping there is an internal mechanism.
Thank you.

**Comment by EricZimmerman** [comment]
i can look into this, but would it be possible to script appcompatparser to write out to a specific directory and your subsequent script can just pick up any file in said directory?

**Comment by PolarBearGod** [comment]
Hey Eric,

Sorry for the delay. To answer your question, as it stands currently I mostly use PowerShell and pass system variables (env:computername, env:systemdrive, etc) and some custom variables (domain name, current user, etc) into the file names to make organization and parsing much easier with all of my other tools. While renaming after execution is not a problem (I currently have it working fine right now), renaming a file that is streamed (read "redirected" out) tends to fail.

Just thinking it would be helpful to be able to pass custom names. If not, no worries. Just passing the idea along. :)

**Comment by EricZimmerman** [comment]
dont know how i left this for so long, but there has been a --csvf switch to do this for a while now. sorry about that!
