### ISSUE TITLE
Where the nuget at?

### ISSUE THREAD

**Issue by agoodhockey** [EricZimmerman/AppCompatCacheParser#5]
hello hermano
u said in the commit there is nuget. but where :angry: ?
ty arigato amigo :)

**Comment by EricZimmerman** [comment]
That message in the commit was for packages that the program uses, not a package for the parser itself

I can add one but if you fork the project and build it you want the DLL as that's what's doing the heavy lifting

**Comment by agoodhockey** [comment]
yo thanks for the fast response bro
but i do need the nuget tho :smile: 
ty

**Comment by EricZimmerman** [comment]
Do you sponsor me on GitHub?

**Comment by EricZimmerman** [comment]
I guess not
